# Generated by Django 4.0.6 on 2022-09-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article_category', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('body', models.CharField(max_length=1500)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
