# Generated by Django 4.0.6 on 2023-02-05 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articles_image_article_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image_article_list',
            field=models.ImageField(upload_to='featured_image'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='featured_image')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articles')),
            ],
        ),
    ]
